coglobal:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'api'
  
  - job_name: 'scraper'
    static_configs:
      - targets: ['scraper:9090']
        labels:
          service: 'scraper'

